# -*- coding: utf-8 -*-
"""rs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1waqQ0scPNn4prUl0KZuqS9yQiBG80kuY
"""

import os
os.environ["OPENBLAS_NUM_THREADS"] = "1"  # optional: avoids noisy OpenBLAS warnings

import numpy as np
from scipy.sparse import csr_matrix
from collections import defaultdict
from tqdm import tqdm
import implicit

# ============================================
# CONFIG
# ============================================
INPUT_PATH = "train.txt"                     # your dataset file
OUTPUT_PATH = "top20_recommendations.txt"    # output file
TOP_K = 20

# ============================================
# 1. LOAD DATA
# Each line: user_id item1 item2 ...
# ============================================
user_items = defaultdict(set)
all_users = set()
all_items = set()

with open(INPUT_PATH, "r") as f:
    for line in f:
        parts = line.strip().split()
        if len(parts) <= 1:
            continue

        u = int(parts[0])
        items = list(map(int, parts[1:]))

        all_users.add(u)
        for it in items:
            user_items[u].add(it)
            all_items.add(it)

# Map raw IDs -> consecutive indices
user2idx = {u: i for i, u in enumerate(sorted(all_users))}
idx2user = {i: u for u, i in user2idx.items()}

item2idx = {it: i for i, it in enumerate(sorted(all_items))}
idx2item = {i: it for it, i in item2idx.items()}

num_users = len(user2idx)
num_items = len(item2idx)

print(f"Users: {num_users}  Items: {num_items}")

# ============================================
# 2. BUILD USER–ITEM SPARSE MATRIX (users x items)
# ============================================
rows, cols, data = [], [], []

for u, items in user_items.items():
    u_idx = user2idx[u]
    for it in items:
        i_idx = item2idx[it]
        rows.append(u_idx)
        cols.append(i_idx)
        data.append(1.0)  # implicit positive interaction

X = csr_matrix((data, (rows, cols)), shape=(num_users, num_items))

# ============================================
# 3. TRAIN ALS MODEL ON USER–ITEM MATRIX
# ============================================
# IMPORTANT: fit on user–item (NOT transposed) for implicit>=0.5
model = implicit.als.AlternatingLeastSquares(
    factors=64,
    regularization=0.01,
    iterations=20,
    random_state=42,
)

print("Training ALS model...")
model.fit(X)  # <- key fix: no transpose here
print("Training complete.")

# ============================================
# 4. GENERATE TOP-20 RECOMMENDATIONS PER USER
# ============================================
print(f"Generating Top-{TOP_K} recommendations for each user...")

with open(OUTPUT_PATH, "w") as out:
    for u_idx in tqdm(range(num_users)):
        u_id = idx2user[u_idx]

        # For implicit, recommend signature is:
        # ids, scores = model.recommend(userid, user_items[userid])
        ids, scores = model.recommend(
            userid=u_idx,
            user_items=X[u_idx],          # single-row CSR (1 x num_items)
            N=TOP_K,
            filter_already_liked_items=True,
        )

        # Map internal item indices back to original item IDs
        rec_items = [idx2item[i] for i in ids]

        # Write: user_id item1 item2 ... item20
        line = " ".join([str(u_id)] + [str(it) for it in rec_items])
        out.write(line + "\n")

print("Done. Recommendations saved to:", OUTPUT_PATH)

!pip install implicit